In [37]:
#importing necesarry library
import pandas as pd
import numpy as np



In [38]:
#reading the file
   #url for dataset of the given problem
df = pd.read_csv('cardeetails1.csv')    #reading csv file

In [39]:
df.head()  #showing value of top 5 rows

Car Name  Monthly Payment  Upfront  Contract Length  Milage  Document Fee  \
0         1           412.36        9               48   10000        239.99   
1         1           391.39       12               48   10000        239.99   
2         1           512.35        1               48   15000        239.99   
3         1           491.86        3               48   15000        239.99   
4         1           464.02        6               48   15000        239.99   

   Average Monthly Cost  Initial Payment  
0                486.09          3711.21  
1                486.08          4696.68  
2                517.35           512.35  
3                517.35          1475.58  
4                517.36          2784.11

In [40]:
df['Car Name'].value_counts()

1    1109
Name: Car Name, dtype: int64

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1109 entries, 0 to 1108
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Car Name              1109 non-null   int64  
 1   Monthly Payment       1109 non-null   float64
 2   Upfront               1109 non-null   int64  
 3   Contract Length       1109 non-null   int64  
 4   Milage                1109 non-null   int64  
 5   Document Fee          1109 non-null   float64
 6   Average Monthly Cost  1109 non-null   float64
 7   Initial Payment       1109 non-null   float64
dtypes: float64(4), int64(4)
memory usage: 69.4 KB


In [42]:
df.describe()

Car Name  Monthly Payment      Upfront  Contract Length        Milage  \
count    1109.0      1109.000000  1109.000000      1109.000000   1109.000000   
mean        1.0       529.422831     6.197475        36.638413  12795.311091   
std         0.0       106.072771     3.972577         9.911340   6824.550581   
min         1.0       311.190000     1.000000        24.000000   5000.000000   
25%         1.0       452.350000     3.000000        24.000000   8000.000000   
50%         1.0       516.360000     6.000000        36.000000  10000.000000   
75%         1.0       591.980000     9.000000        48.000000  20000.000000   
max         1.0       915.830000    12.000000        48.000000  30000.000000   

       Document Fee  Average Monthly Cost  Initial Payment  
count  1.109000e+03           1109.000000      1109.000000  
mean   2.399900e+02            612.022011      3065.638215  
std    2.843453e-14            114.801126      1840.999319  
min    2.399900e+02            387.500000       382.500000  
25%    2.399900e+02            530.960000      1504.080000  
50%    2.399900e+02            599.920000      3111.420000  
75%    2.399900e+02            690.360000      4561.650000  
max    2.399900e+02            921.240000      7535.960000

In [43]:
df.isna().sum()   #is there any missing value

Car Name                0
Monthly Payment         0
Upfront                 0
Contract Length         0
Milage                  0
Document Fee            0
Average Monthly Cost    0
Initial Payment         0
dtype: int64

In [44]:
x = df.drop(['Monthly Payment','Average Monthly Cost'],axis=1)    #independent variable
x

Car Name  Upfront  Contract Length  Milage  Document Fee  \
0            1        9               48   10000        239.99   
1            1       12               48   10000        239.99   
2            1        1               48   15000        239.99   
3            1        3               48   15000        239.99   
4            1        6               48   15000        239.99   
...        ...      ...              ...     ...           ...   
1104         1        1               48    5000        239.99   
1105         1        3               48    5000        239.99   
1106         1        6               48    5000        239.99   
1107         1        9               48    5000        239.99   
1108         1       12               48    5000        239.99   

      Initial Payment  
0             3711.21  
1             4696.68  
2              512.35  
3             1475.58  
4             2784.11  
...               ...  
1104           382.50  
1105          1101.60  
1106          2078.49  
1107          2950.71  
1108          3734.24  

[1109 rows x 6 columns]

In [45]:
y = df[['Monthly Payment']]
y#dependent variable

Monthly Payment
0              412.36
1              391.39
2              512.35
3              491.86
4              464.02
...               ...
1104           382.50
1105           367.20
1106           346.42
1107           327.86
1108           311.19

[1109 rows x 1 columns]

In [46]:
#Splitting the data in training and testing
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [47]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression(normalize=True)
lm.fit(x_train,y_train)  #fitting the model

lm.score(x_train,y_train)*100

73.96821551983479

In [48]:
#predicting the value
y_preds = lm.predict(x_test)
print(y_preds)

[[410.63645629]
 [424.44472963]
 [369.76474328]
 [628.1452498 ]
 [570.28905538]
 [461.02824842]
 [547.15451135]
 [539.3749303 ]
 [528.28576995]
 [550.65413846]
 [567.59282442]
 [623.19811756]
 [428.63944118]
 [448.40598435]
 [610.24932425]
 [353.98696075]
 [463.894329  ]
 [373.25625405]
 [570.28859511]
 [636.24243859]
 [629.28867937]
 [335.75040399]
 [431.08907013]
 [401.85377563]
 [590.90734803]
 [402.03264038]
 [508.61993821]
 [474.71858917]
 [590.93695982]
 [389.02426518]
 [250.1358904 ]
 [571.45307283]
 [631.83078432]
 [639.33705372]
 [625.18597033]
 [585.74632208]
 [585.85383314]
 [555.86811092]
 [543.86856255]
 [569.37342946]
 [516.22642385]
 [439.10055837]
 [550.30320321]
 [525.84687447]
 [576.09487242]
 [495.64180736]
 [340.99087939]
 [532.62406444]
 [480.4644006 ]
 [488.16505627]
 [616.10191193]
 [485.32139145]
 [625.16271654]
 [659.36157145]
 [443.66751332]
 [629.8999798 ]
 [461.51779108]
 [499.85353484]
 [597.37342317]
 [528.37327659]
 [615.83236354]
 [252.01870838]
 [528.24

In [49]:
# Plotting the regression line
coefficient = lm.coef_
intercept  = lm.intercept_

In [52]:
df['Milage'].value_counts()

20000    210
15000    210
5000     208
10000    206
8000     205
30000     70
Name: Milage, dtype: int64

In [35]:
from numpy import argmax
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = np.array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print("encoded hai",integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded)])
print(inverted)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
encoded hai [0 0 2 0 1 1 2 0 2 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['cold']


In [56]:
!pip3 install scikit-learn==0.19.0

  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Asus\anaconda32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Asus\\AppData\\Local\\Temp\\pip-install-fs9699p_\\scikit-learn\\setup.py'"'"'; __file__='"'"'C:\\Users\\Asus\\AppData\\Local\\Temp\\pip-install-fs9699p_\\scikit-learn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Asus\AppData\Local\Temp\pip-wheel-kqj1gyml'
       cwd: C:\Users\Asus\AppData\Local\Temp\pip-install-fs9699p_\scikit-learn\
  Complete output (625 lines):
  Partial import of sklearn during the build process.
  blas_opt_info:
  blas_mkl_info:
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
    libraries mkl_rt not found in ['C:\\Users\\Asus\\anaconda32\\lib', 'C:\\', 'C:\\Users\\Asus\\anaco

  Running setup.py clean for scikit-learn
Failed to build scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.23.2
    Uninstalling scikit-learn-0.23.2:
      Successfully uninstalled scikit-learn-0.23.2
    Running setup.py install for scikit-learn: started
    Running setup.py install for scikit-learn: finished with status 'error'
  Rolling back uninstall of scikit-learn
  Moving to c:\users\asus\anaconda32\lib\site-packages\scikit_learn-0.23.2.dist-info\
   from C:\Users\Asus\anaconda32\Lib\site-packages\~cikit_learn-0.23.2.dist-info
  Moving to c:\users\asus\anaconda32\lib\site-packages\sklearn\
   from C:\Users\Asus\anaconda32\Lib\site-packages\~klearn


  don't know how to compile Fortran code on platform 'nt'
    NOT AVAILABLE
  
  atlas_3_10_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas not found in ['C:\\Users\\Asus\\anaconda32\\lib', 'C:\\', 'C:\\Users\\Asus\\anaconda32\\libs']
    NOT AVAILABLE
  
  atlas_3_10_blas_info:
    libraries satlas not found in ['C:\\Users\\Asus\\anaconda32\\lib', 'C:\\', 'C:\\Users\\Asus\\anaconda32\\libs']
    NOT AVAILABLE
  
  atlas_blas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\Asus\\anaconda32\\lib', 'C:\\', 'C:\\Users\\Asus\\anaconda32\\libs']
    NOT AVAILABLE
  
  atlas_blas_info:
    libraries f77blas,cblas,atlas not found in ['C:\\Users\\Asus\\anaconda32\\lib', 'C:\\', 'C:\\Users\\Asus\\anaconda32\\libs']
    NOT AVAILABLE
  
  accelerate_info:
    NOT AVAILABLE
  
  C:\Users\Asus\anaconda32\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Optimized (vendor) Blas libraries are not found.
   

In [54]:
import pickle
with open("new_work.pkl","wb") as f:
    pickle.dump(lm,f)